import test from "node:test";
import nodeAssert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, readdirSync, statSync, utimesSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const cli = join(process.cwd(), "dist/src/dream/cli.js");
const assert: any = nodeAssert;
assert.match = (value: string, expected: RegExp | string) => nodeAssert.ok(typeof expected === "string" ? value.includes(expected) : expected.test(value));
function fixture() { const home = mkdtempSync(join(tmpdir(), "dream-")); mkdirSync(join(home, "pi/session"), { recursive: true }); return home; }
function note(home: string, session: string, name: string, body: string, window: string) { const dir = join(home, "pi/session", session); mkdirSync(dir, { recursive: true }); writeFileSync(join(dir, name), `---\nscope: session\norigin: self\nstatus: active\nsource_window: ${window}\ncreated_at: 2020-01-01T00:00:00.000Z\nupdated_at: 2020-01-01T00:00:00.000Z\nlast_accessed: 2020-01-01T00:00:00.000Z\naccess_count: 0\n---\n\n${body}`); }
function worker(home: string, manifest: unknown, sentinel?: string) { const file = join(home, "worker.mjs"); writeFileSync(file, `import {writeFileSync} from 'node:fs'; ${sentinel ? `writeFileSync(${JSON.stringify(sentinel)}, 'spawned');` : ""} process.stdin.resume(); process.stdin.on('end',()=>process.stdout.write(${JSON.stringify(JSON.stringify(manifest))}));`); return `node ${file}`; }
function run(home: string, extra: string[] = []) { return spawnSync(process.execPath, [cli, "--notes-home", home, ...extra], { encoding: "utf8" }); }
function old(path: string) { const d = new Date(Date.now() - 48 * 3600_000); utimesSync(path, d, d); }

test("dream time gate skips first, names reason, and does not spawn", () => { const h=fixture(); const sentinel=join(h,"sentinel"); const lock=join(h,".dream.lock"); writeFileSync(lock,"999999"); const fresh=new Date(); utimesSync(lock,fresh,fresh); const r=run(h,["--worker",worker(h,{report:"x"},sentinel)]); assert.equal(r.status,0); assert.match(r.stdout,"time gate"); assert.equal(existsSync(sentinel),false); });
test("material gate skips when too few session directories changed", () => { const h=fixture(); const lock=join(h,".dream.lock"); writeFileSync(lock,"999999"); old(lock); note(h,"only","a.md","a","w"); const r=run(h,["--min-sessions","3","--worker",worker(h,{report:"x"})]); assert.equal(r.status,0); assert.match(r.stdout,"material gate"); });
test("force bypasses time and material gates and fake worker runs", () => { const h=fixture(); const r=run(h,["--force","--worker",worker(h,{report:"forced"})]); assert.equal(r.status,0); assert.match(readFileSync(readdirSync(join(h,"dreams")).map(x=>join(h,"dreams",x))[0],"utf8"),"forced"); });
test("live PID lock excludes and dead PID is reclaimed", () => { const h=fixture(); const lock=join(h,".dream.lock"); writeFileSync(lock,String(process.pid)); const r=run(h,["--force","--worker",worker(h,{report:"no"})]); assert.equal(r.status,0); assert.match(r.stdout,"lock gate"); writeFileSync(lock,"999999"); old(lock); const ok=run(h,["--force","--worker",worker(h,{report:"reclaimed"})]); assert.equal(ok.status,0); });
test("fake worker manifest merges recurrence, proposes global promotion, trashes, and reports", () => { const h=fixture(); note(h,"dream","a.md","one","window-a"); note(h,"dream","b.md","two","window-b"); note(h,"dream","trash.md","gone","window-c"); const m={merge:[{into:"a.md",from:["b.md"]}],promote:[{path:"a.md",to:"global",reason:"shared"}],trash:[{path:"trash.md",reason:"obsolete"}],report:"I dreamed on 2026-09-19."}; const r=run(h,["--force","--worker",worker(h,m)]); assert.equal(r.status,0,r.stderr); const merged=readFileSync(join(h,"pi/session/dream/a.md"),"utf8"); assert.match(merged,"one"); assert.match(merged,"two"); assert.match(merged,"recurrence_count: 1"); assert.match(readFileSync(join(h,"pi/session/dream/b.md"),"utf8"),"status: superseded"); assert.equal(existsSync(join(h,"pi/session/dream/trash.md")),false); const reports=readdirSync(join(h,"dreams")); const report=readFileSync(join(h,"dreams",reports[0]),"utf8"); assert.match(report,"I dreamed"); assert.match(report,"proposal: promote"); assert.match(report,"trashed"); });
test("invalid manifest path makes zero writes and exits nonzero", () => { const h=fixture(); note(h,"s1","a.md","one","w"); const before=readFileSync(join(h,"pi/session/s1/a.md"),"utf8"); const r=run(h,["--force","--worker",worker(h,{merge:[{into:"missing.md",from:["a.md"]}],report:"bad"})]); assert.notEqual(r.status,0); assert.match(r.stderr,"missing.md"); assert.equal(readFileSync(join(h,"pi/session/s1/a.md"),"utf8"),before); assert.equal(existsSync(join(h,"dreams")),false); });
test("failed run restores prior lock mtime", () => { const h=fixture(); const lock=join(h,".dream.lock"); writeFileSync(lock,"999999"); const prior=Date.now()-48*3600_000; utimesSync(lock,new Date(prior),new Date(prior)); const r=run(h,["--force","--worker",worker(h,{merge:[{into:"missing",from:[]}],report:"x"})]); assert.notEqual(r.status,0); assert.ok(Math.abs(statSync(lock).mtimeMs-prior)<2000); });
